package com.updapy.model.enumeration;

public enum ApplicationCategory {
	// GAMES, EDUCATION, TRAVEL, SPORT, FOOD, MEDICAl, FINANCE,
	INTERNET, SOCIAL_COMMUNICATION, TEXT, IMAGE, MUSIC, VIDEO, SECURITY, TOOLS, DEVELOPMENT, SYSTEM, SYSTEM_OTHER, MISC;
}
