package com.updapy.model.enumeration;

public enum TypeRetrievalError {
	REMOTE_URL_BASE_ERROR, REMOTE_URL_VERSION_ERROR, LOCAL_URL_VERSION_ERROR, REMOTE_PARSING_ERROR, REMOTE_NEW_VERSION_WITH_NUMBER_NOT_CONSISTENT, SAME_VERSION_DIFFERENT_URL;
}
